# tasks/main.yml
---
- name: Include common tasks
  include_tasks: common.yml

- name: Add exptcp object
  include_tasks: add_exptcp.yml
  when: action == "add"

- name: Delete exptcp object
  include_tasks: delete_exptcp.yml
  when: action == "delete"

- name: Get exptcp object
  include_tasks: get_exptcp.yml
  when: action == "get"

- name: List exptcp objects
  include_tasks: list_exptcp.yml
  when: action == "list"